/pose_node:
  ros__parameters:
    goal_point: [
                -32.53, 4.70, 0.785,
                -32.72, 20.05, 0.0485,
                -7.67, 20.07, -1.47,
                -7.78, 6.18, 3.12
                
                ]
       
    initial_point: [-7.78, 6.18, 3.12]

    use_sim_time: false